config/routes.rb
Rails.application.routes.draw do

	root "posts#index"
  devise_for :users
  ActiveAdmin.routes(self)
  resources :users
  resources :posts
  resources :reviews
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  mount_uploader :image, ImageUploader

  def score
  	score = 0
  	count = 0
  	self.reviews.each do |review|
  		score += review.rate
  		count += 1
  	end

  	return 0 if count == 0
  	average = score / count

  	return average  	
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts, dependent: :destroy
	has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :destroy]

	def index
		@posts = Post.all.reverse	
	end

	def show
		@post = Post.find(params[:id])
	end

	def new	
		@user = current_user
	end

	def create
  	@user = current_user

  	if @user.posts.create(post_params)
  		redirect_to @user, notice: 'Photo was successfully created.'
  	else
  		redirect_to @user, notice: 'Smthng wrong.'
  	end
  end

  def destroy
  	post = Post.find(params[:id])
  	
  	if post.user == current_user
  		post.destroy		
			flash[:notice] = "Post was destroyed."
			redirect_to user_path(post.user)
		else
			flash[:notice] = "No access."
			redirect_to user_path(post.user)
		end
	end

	private

	def post_params
		params.require(:post).permit(:title, :image)		
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
		post = Post.find(params[:review][:post_id])
		user = User.find(params[:review][:user_id])
		rate = params[:review][:rate]
		body = params[:review][:body]

		@review = Review.new(rate: rate, body: body, post_id: post.id, user_id: user.id)

		if @review.save
			flash[:notice] = "Review created."
			redirect_to post_path(post)
		else
			flash[:notice] = "Review not created."
			redirect_to post_path(post)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Photo Gallery</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<%= link_to "Photo Gallery", root_path, class: 'navbar-brand'%>
				<% if notice %>
				<p class="navbar-text" id="alert"><%= notice %></p>
				<% end %>
				<% if alert %>
				<p class="navbar-text" id="alert"><%= alert %></p>
				<% end %>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog"></span></a>
						<ul class="dropdown-menu">
							<li><%= link_to('Profile', user_path(current_user)) %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to('Settings', edit_user_registration_path) %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
						</ul>
					</li>
					<% else %>
					<li><%= link_to('Sign in', new_user_session_path) %></li>
					<li><%= link_to('Sign up', new_user_registration_path) %></li>
					<% end %>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	
	<div class="container">		
		<%= yield %>
	</div>
	<script type="text/javascript">
		$("#alert").delay(2500).fadeOut();
	</script>
</body>
</html>

app/views/posts/_post.html.erb
<div class="col-md-3 col-sm-6 fixed">
	<span class="thumbnail text-center">
		<%= image_tag post.image_url(:normal).to_s %>
		<h4><%= link_to post.title, post_path(post), class: "text-danger" %></h4>
		<h5>By: <%= link_to post.user.name, user_path(post.user), class: "text-danger" %> </h5>
	</span>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">   
  <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= simple_form_for(@user.posts.build, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.input :title %>
	<%= f.file_field :image, required: true %>
	<%= f.button :submit %>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<span class="thumbnail text-center">
	<%= image_tag @post.image_url(:huge).to_s %>
	<h4>By: <%= link_to @post.user.name, user_path(@post.user), class: "text-danger" %> </h4>
	<h4>Score: <%= @post.score %> </h4>
</span>

<h2>Add comment:</h2>

<%= render "reviews/form" if current_user != nil %>

<%= render @post.reviews %>

app/views/reviews/_form.html.erb
<%= simple_form_for(Review.new, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.input :body, required: true %>
	<%= f.input :rate, collection: 1..5, required: true %>

	<%= f.hidden_field :user_id, value: current_user.id %>
	<%= f.hidden_field :post_id, value: @post.id %>

	<%= f.button :submit %>
<% end %>

app/views/reviews/_review.html.erb
<h4>By: <%= review.user.name %>, score: <%= review.rate %></h4>
<p><%= review.body %></p>
<hr>

app/views/users/show.html.erb
<h2><%= @user.name + "'s" %> profile</h2>

<% if @user == current_user %>
<div class="area">
	<%= content_tag(:big, "My photos")%>
	<%= link_to "Create new photo", new_post_path, class: "btn btn-primary" %>
</div>
<% end %>

<div class="container">
	<table class="table">
		<tr>
			<th>Photo</th>
			<th>Title</th>
			<th>Actions</th>
		</tr>
		<% @user.posts.each do |post| %>
			<tr>
				<td><%= image_tag post.image_url(:thumb).to_s %></td>
				<td><%= post.title %></td>
				<td><%= link_to "Delete", post_path(post), method: :delete if post.user == current_user %></td>
			</tr>
		<% end %>		
	</table>
</div>